### PR TITLE
simple "clone entity" feature; creates a copy of the source entity an…

### PR DESCRIPTION
**Pull request by anegrin**
simple "clone entity" feature; creates a copy of the source entity and redirect user to new entity editing

### CODE REVIEW

**Comment by ikostenko** [comment]
*Issues found on lightadmin-sandbox application*
Impossible to clone domain entities for Addresses, Customers, LineItems, Orders, Products - 404 page is shown an exception
Example of exception for Addresses domain 
```javax.validation.ConstraintViolationException: Validation failed for classes [org.lightadmin.demo.model.Address] during persist time for groups [javax.validation.groups.Default, ] List of constraint violations:[ ConstraintViolationImpl{interpolatedMessage='may not be empty', propertyPath=country, rootBeanClass=class org.lightadmin.demo.model.Address, messageTemplate='{org.hibernate.validator.constraints.NotBlank.message}'} ConstraintViolationImpl{interpolatedMessage='may not be empty', propertyPath=city, rootBeanClass=class org.lightadmin.demo.model.Address, messageTemplate='{org.hibernate.validator.constraints.NotBlank.message}'} ConstraintViolationImpl{interpolatedMessage='may not be empty', propertyPath=street, rootBeanClass=class org.lightadmin.demo.model.Address, messageTemplate='{org.hibernate.validator.constraints.NotBlank.message}'} ]```

However, it is possible to clone an entity for Discounts domain

**Comment by anegrin** [comment]
i'll check that

**Comment by anegrin** [comment]
found out: this is becouse Address has no writeable properties... (no setters)

**Comment by ikostenko** [comment]
> found out: this is becouse Address has no writeable properties... (no setters)

Thank you, Alessandro. Adding setters fixed the issue.

However, the following issues were found: 

1. Impossible to clone an entity with validated fields (f.ex., `@Future`, `@Column(unique = true)`: exceptions are thrown on attempt to clone: 
```javax.validation.ConstraintViolationException: Validation failed for classes [org.lightadmin.demo.model.Customer] during persist time for groups [javax.validation.groups.Default, ] List of constraint violations:[ ConstraintViolationImpl{interpolatedMessage='must be in the future', propertyPath=registrationDate, rootBeanClass=class org.lightadmin.demo.model.Customer, messageTemplate='{javax.validation.constraints.Future.message}'} ]```

```integrity constraint violation: unique constraint or index violation: IX_CUSTOMER_EMAIL```
2. Impossible to clone an entity with `@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)`: the following exception is thrown on attempt to clone: 

```org.springframework.orm.jpa.JpaSystemException: Don't change the reference to a collection with delete-orphan enabled : org.lightadmin.test.model.TestOrder.lineItems; nested exception is org.hibernate.HibernateException: Don't change the reference to a collection with delete-orphan enabled : org.lightadmin.test.model.TestOrder.lineItems```
3. Impossible to clone an entity with a `@Transient` field: the following exception is thrown on attempt to clone:

```org.springframework.beans.FatalBeanException: Could not copy property 'orderTotal' from source to target; nested exception is java.lang.reflect.InvocationTargetException```

**Comment by anegrin** [comment]
all these behaviours are quite "normal". the fact is that i clone item silently, save it, and then redirect to edit. if there are constraints like unique, or orphan removal, the clone strategy is quite difficult to "guess"

maybe clone action shuold be configurable (allowed/not allowed) via admin component becouse user can always implement the correct strategy by overriding onBeforeCreate on a registered entity listener

**Comment by anegrin** [comment]
please check [Commit  8a4acc0](https://github.com/atklab/light-admin/commit/8a4acc03860155742ef9903fb3a74d5929643a83) and try to clone and Address. i believe this is a nice way for developers to implement their own cloning strategy where default strategy fails

**Pull request closed without merging**
