### PR TITLE
n2many relations did not keep order; fixed using a parallel hidden select

### PR DESCRIPTION
**Pull request by anegrin**
n2many relations did not keep order; fixed using a parallel hidden select keeping track of order and reordering original select (now suffixed with -n2mall) on form load

### CODE REVIEW

**Comment by anegrin** [comment]
added some fixes (stupid me... :/ )

**Comment by max-dev** [comment]
Thanks :) we'll test it and merge.

**Comment by ikostenko** [comment]
@anegrin In order for us to test the fix, could you please describe the original issue? Preferrably, could you please share your entities configuration and the scenario?

**Comment by anegrin** [comment]
yep! i have gallery relate 1 to n with images

gallery: https://gist.github.com/anegrin/a981bb2b13e5bbc3c670
image: https://gist.github.com/anegrin/94e9593f5969bda5f5e7

saving a gallery with images does not keep the order of images: images are always sorted on their "natural" order using image admin nameField; this is becouse the form just use a hidden multiselect with "selected"

with this fix order is mantained becouse i use a parallel select where images (in this case) are correctly sorted

**Pull request closed without merging**
